### ISSUE TITLE
Unable to add some file references to Xcode project

### ISSUE THREAD

**Issue by melisa-dlg** [RedMadRobot/figma-export#100]
Hi! I have just done the setup and wanted to try it out with my project but I keep getting that error when exporting colors and typography. I have followed the setup of the yaml file with `xcassetsInMainBundle` set as true and the file paths, as well as the  `generateLabels`and `labelsDirectory`. Do you what could be going wrong? thanks!

**Comment by subdan** [comment]
Hi. Could you show me your yaml file?

**Comment by melisa-dlg** [comment]
file sent to your email

**Comment by subdan** [comment]
fixed in 0.23.1
