### ISSUE TITLE
Android Dark Color Export

### ISSUE THREAD

**Issue by kaiwidmer** [RedMadRobot/figma-export#110]
I've experienced an issue, while exporting colors (light and dark) for android from one figma file, while dark-colors are suffixed with "_dark".

The figma file contains 5 colors, two are defined for dark and light, three of them have no dark definition.

The following warning appears, as expected:
> ⚠️ The following assets will be considered universal because they are not found in the dark palette: color1, color2, color3

But as a result, my colors-night-xml contains no values at all.

If I remove this three colors without dark definition, everything is working fine.
Also, if I remove the property _useSingleFile_, all colors are exported correctly into colors.xml.

**Comment by subdan** [comment]
I'll check it out and get back to you in a couple of days.

**Comment by subdan** [comment]
I've fixed an issue. Please update to the new version 0.24.3 in 15 min and check again.

**Comment by kaiwidmer** [comment]
thank you very much, looks good now.
