### ISSUE TITLE
Color icons

### ISSUE THREAD

**Issue by alexey1312** [RedMadRobot/figma-export#114]
Hey!
I have several icons, the color of which I will set in the code, they have a `renderMode: template `property by default.
But there are a few icons that I would like to assign the `renderMode: default` property.
How can I best do it?

**Comment by subdan** [comment]
Hi. There are two solutions:
1. You can use two figma-export.yml files. Each one will export icons from different frames. One frame will contains icons for exporting with template rendering mode and another with default rendering mode.
2. Just add “Template” string at the end of an icon name and use default rendering mode for all the icons. If name of the icon ends with “Template” it will use template rendering mode. More info here https://telegra.ph/Rezhimy-Render-As-12-25

**Comment by subdan** [comment]
Hi. There are two solutions:
1. You can use two figma-export.yml files. Each one will export icons from different frames. One frame will contains icons for exporting with template rendering mode and another with default rendering mode.
2. Just add “Template” string at the end of an icon name and use default rendering mode for all the icons. If name of the icon ends with “Template” it will use template rendering mode. More info here https://telegra.ph/Rezhimy-Render-As-12-25

**Comment by alexey1312** [comment]
Nice! Thank You!
