### ISSUE TITLE
When I run the figma-export command, it report following error

### ISSUE THREAD

**Issue by fanthus** [RedMadRobot/figma-export#12]
➜  LJComponentManager git:(master) ✗ figma-export colors -i figma-export.yaml
2020-07-09T17:24:36+0800 info: Using FigmaExport to export colors.
2020-07-09T17:24:36+0800 info: Fetching colors. Please wait...
Error: Figma API: Not found

**Comment by fanthus** [comment]
I already configure figma token in .zshrc file.

**Comment by subdan** [comment]
Hi. The error says that it can't find your Figma file. Please, check this property `figma.lightFileId`

**Comment by fanthus** [comment]
thanks, I have fixed the lightField, but it report the following error
```
2020-07-09T17:59:17+0800 info: Fetching images info from Figma. Please wait...
Error: Figma API: {"params":["file_key"],"query":["ids"]} are required.
```

**Comment by subdan** [comment]
Figma API can't find image components.

Ensure that you have a frame with "Illustrations" name. The frame must contains a components. These components must be published to the Team Library.

**Comment by fanthus** [comment]
thanks
