### ISSUE TITLE
Error when export Typography

### ISSUE THREAD

**Issue by voragomod** [RedMadRobot/figma-export#126]
When I try export typography get error, at the same time colors, icons and pictures are loaded perfectly, thank you very much!

Error:
figma-export typography

2021-10-30T13:01:12+0300 info com.redmadrobot.figma-export : Using FigmaExport 0.29.0 to export typography.
2021-10-30T13:01:12+0300 info com.redmadrobot.figma-export : Fetching text styles. Please wait...
Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "nodes", intValue: nil), _JSONKey(stringValue: "329:9708", intValue: nil), CodingKeys(stringValue: "document", intValue: nil), CodingKeys(stringValue: "style", intValue: nil), CodingKeys(stringValue: "fontPostScriptName", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))

Our typography:
![Снимок экрана 2021-10-30 в 13 05 16](https://user-images.githubusercontent.com/32967155/139528649-9a7fe585-3b71-4526-9ee3-e374d4c875ef.png)

**Comment by subdan** [comment]
Hello. Could you please show me your `figma-export.yaml` file?

**Comment by voragomod** [comment]
The problem definitely cannot be in `figma-export.yaml`, bcs if I set test project id from article I successfully fetch fonts.

I'll ask our designer to make a project with only fonts and give an identifier, is that okay?

![Снимок экрана 2021-11-01 в 00 57 41](https://user-images.githubusercontent.com/32967155/139602523-210b72f0-a937-4662-8d8e-fc7aa23fd3bf.png)

**Comment by subdan** [comment]
> I'll ask our designer to make a project with only fonts and give an identifier, is that okay?

Yes.

**Comment by voragomod** [comment]
Hi, test project:
https://www.figma.com/file/N8ZkMr3BVjoZZR9BE33Whk/Typography-TEST?node-id=0%3A1

**Comment by subdan** [comment]
I've found a bug, fix it and release a new version. Please update to the 0.31.1 and check again.

**Comment by voragomod** [comment]
Great, now everything works, thanks a lot!
