### ISSUE TITLE
Icons failed to be exported when the component contains a description

### ISSUE THREAD

**Issue by agarcia-wish** [RedMadRobot/figma-export#129]
Notice a problem where the icons are failing to get exported if the field description is filled in Figma. Attached a screenshot
<img width="246" alt="Screen Shot 2021-11-16 at 3 32 09 PM" src="https://user-images.githubusercontent.com/84881359/142061172-2b71d5b0-42db-44ac-a974-4a3d259a1208.png">

**Comment by subdan** [comment]
Thanks. This is a bug. I will fix it by the end of the week and release a new version.

**Comment by subdan** [comment]
Please update to the latest version and check again.

**Comment by agarcia-wish** [comment]
Thanks @subdan, it works as expected. 💯
