### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by subdan** [RedMadRobot/figma-export#13]
A lot of users see these errors:
`Error: Figma API: {"params":["file_key"],"query":["ids"]} are required.`
`Error: Figma API: Not found`

It will be cool to give users more info why this error happens.

**Comment by andreyoshev** [comment]
А как эту ошибку победить?

**Comment by subdan** [comment]
Проверь что все правила из раздела [Design requirements](https://github.com/RedMadRobot/figma-export#design-requirements) соблюдены. Важно чтобы все цветовые стили и компоненты были опубликованы в Team Library.

Если Figma файл организован правильно и все компоненты и стили опубликованы, но ошибка все-равно возникает то можешь прислать yaml файл и дать ссылку на Figma файл?

**Comment by subdan** [comment]
Обычно ошибка `"query":["ids"]} are required.` возникает если в Team Library ничего не найдено.

**Comment by andreyoshev** [comment]
@subdan да, нашел где есть, работает! Кайфую :)

**Comment by subdan** [comment]
Супер!

**Comment by andreyoshev** [comment]
@subdan Неудобно, что он не удаляет старые: было, например, gray_one - сделал экспорт, переименовал в Gray 1 - сделал экспорт, в результате оба цвета в Colors :/

**Comment by subdan** [comment]
Странно. Он должен удалять старые цвета. Сейчас проверю.

**Comment by subdan** [comment]
Да, есть баг. Исправлю в ближайшее время.

**Comment by subdan** [comment]
Исправил и сделал релиз. Можешь обновиться и проверить.

**Comment by andreyoshev** [comment]
@subdan работает 👍🏻
