### ISSUE TITLE
Export png format with ios images

### ISSUE THREAD

**Issue by lowfiend** [RedMadRobot/figma-export#134]
I see config.md ios images not found format parameter.
It export default is svg. Will add format parameter in future?

**Comment by subdan** [comment]
**FigmaExport** export images in PNG format. Which format do you want to use and why PNG format doesn't work for you?

**Comment by lowfiend** [comment]
I want to export ios images with png. But yaml file ios images option can't use format with png.So it export always is svg.

**Comment by lowfiend** [comment]
![1639093483175](https://user-images.githubusercontent.com/9345164/145493109-37ded2c7-f1e5-415a-bc7e-1ddf25c277ac.png)

**Comment by subdan** [comment]
> I want to export ios images with png. But yaml file ios images option can't use format with png.So it export always is svg.

**FigmaExport** always export images in PNG format. You don't need to specify format.

> So it export always is svg.

Remove `android` options in the `figma-export.yml` file. When `figma-export.yml` file contains `android.images.format` value it tries to export images in SVG format. It is a bug. I will fix it.

**Comment by Neyo-WM** [comment]
ok thanks. 

> Remove android options in the figma-export.yml file.

 it works.

**Comment by lowfiend** [comment]
ok thanks.

> Remove android options in the figma-export.yml file

it's work.
