### ISSUE TITLE
figma-export icons android fails 

### ISSUE THREAD

**Issue by eriksquare** [RedMadRobot/figma-export#138]
export icons fails on 0.31.4

i use the tool to export icons to android vector drawable, now this is failing after download:

```
2022-01-11T18:43:54+0100 info com.redmadrobot.figma-export.file-downloader : Downloaded 117/117
2022-01-11T18:43:54+0100 info com.redmadrobot.figma-export : Converting SVGs to XMLs...
Error: The file “vd-tool” doesn’t exist.
```
if i manually invoke vd-tool on the same terminal it actually runs it so it is correctly in the PATH

for context i'm on mac 12.1 on apple silicon

**Comment by subdan** [comment]
Thanks for the issue, **eriksquare**. I will add support for M1 this week.

**Comment by subdan** [comment]
I've fixed the issue. Please, update to the latest version and check again.🤞

**Comment by eriksquare** [comment]
yeah it works! thank you for the quick reply!
