### ISSUE TITLE
figma-export images fails for android

### ISSUE THREAD

**Issue by eriksquare** [RedMadRobot/figma-export#140]
on 0.31.5  :

```
2022-01-12T12:08:02+0100 info com.redmadrobot.figma-export : Converting PNG files to WebP...
Error: The file “cwebp” doesn’t exist.
```
from same terminal cwepb actually runs

this issue is similar to https://github.com/RedMadRobot/figma-export/issues/138
same setup mac 12.1 and apple silicon

**Comment by subdan** [comment]
Sorry, I forget about `cwebp` when I was fixing path to `vd-tool`. I will fix it in a couple of days.

**Comment by subdan** [comment]
I've fixed the issue. Please, update to the latest version 0.31.6 and check again.
