### ISSUE TITLE
Use Stencil to create template for files

### ISSUE THREAD

**Issue by antranapp** [RedMadRobot/figma-export#142]
As far as I can see, all the code that will be generated are hard-coded directly in the source code.

It would be great if we can customise the code template, without changing the source code of figma-export directly.

One idea is to use [Stencil](https://github.com/stencilproject/Stencil) for exporting code templates. The main package just provides all required information for the template, and the users of `figma-export` can customise the template according to their needs.

**Comment by subdan** [comment]
Thanks, @antranapp, this is great idea. I will add Stencil support.

**Comment by subdan** [comment]
Hello, @antranapp. I've added support for custom Stencil Templates in the [latest](https://github.com/RedMadRobot/figma-export/releases/tag/0.32.0) version.
