### ISSUE TITLE
Conflict with other packages using Stencil from official repo

### ISSUE THREAD

**Issue by Fedos** [RedMadRobot/figma-export#149]
Using Stencil from custom fork turns out a bad idea

**Comment by subdan** [comment]
Could you please explain why it is a bad idea?

**Comment by Fedos** [comment]
I'm using Stencil myself from original repo in other packages and now project doesn't build due to conflicts, so I have to stay at the previous version of figma-export.

**Comment by subdan** [comment]
Do you connect FigmaExport to your project via SPM?

**Comment by subdan** [comment]
I've released [a new version](https://github.com/RedMadRobot/figma-export/releases/tag/0.32.1) where using original Stencil.

**Comment by Fedos** [comment]
Along with my own exporters for Figma styles and some other exporters which use original Stencil
