### ISSUE TITLE
High contrast for colors

### ISSUE THREAD

**Issue by alexey1312** [RedMadRobot/figma-export#151]
Hey! Is there an option for color to specify a high contrast color? If not, what is the best way to do it?

<img width="251" alt="CleanShot 2022-02-21 at 17 35 50@2x" src="https://user-images.githubusercontent.com/36570774/154975758-55242fa3-af2f-4ba6-8c5c-973f16450359.png">

**Comment by subdan** [comment]
Unfortunately, no. This is very rarely used in iOS apps.

**Comment by alexey1312** [comment]
It is, a good practice to make the interface more accessible. 
[WCAG](https://www.w3.org/TR/WCAG20-TECHS/SL13.html) has recommendations on this.
It seems to be cool if the utility has this feature.

**Comment by subdan** [comment]
Do you work on a project that support high contrast colors?

**Comment by alexey1312** [comment]
We are now moving to a new palette of colors in which this support will be)

**Comment by subdan** [comment]
Can you please show or tell me how your designers will support high contrast color palette in Figma?

For example, there is a `button_primary` color. Will it be represented in the list of color styles in four variants?

- button_primary
- button_primary_high_contrast
- button_primary_dark
- button_primary_dark_high_contrast

Or will each color palette be in a separate Figma file?

**Comment by alexey1312** [comment]
Each color palette will be in a separate Figma file:
```
 light
 dark
 light_high_contrast
 dark_high_contrast
```
I think, we need to add 2 optional parameters, identifiers of the file containing  light_high_contrast color palette and dark_high_contrast color palette.

**Comment by subdan** [comment]
> I think, we need to add 2 optional parameters, identifiers of the file containing light_high_contrast color palette and dark_high_contrast color palette.

Yes. Do you want to implement it by yourself? ☺️

**Comment by alexey1312** [comment]
yep, i think i can do it

**Comment by subdan** [comment]
Closed in #157
