### ISSUE TITLE
Homebrew installation error

### ISSUE THREAD

**Issue by margarita-v** [RedMadRobot/figma-export#155]
macOS Big Sur, 11.5.2

Homebrew 3.4.0
Homebrew/homebrew-core (git revision 5067da87154; last commit 2022-03-02)
Homebrew/homebrew-cask (git revision f09b1c6501; last commit 2022-03-02)

Run `brew install RedMadRobot/formulae/figma-export` according README.
Error during installation:
```
Error: Invalid formula: /opt/homebrew/Library/Taps/redmadrobot/homebrew-formulae/catbird.rb
catbird: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the redmadrobot/formulae tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/redmadrobot/homebrew-formulae/catbird.rb:7

Error: Cannot tap redmadrobot/formulae: invalid syntax in tap!
```

**Comment by Alexander-Ignition** [comment]
Fixed in: https://github.com/RedMadRobot/homebrew-formulae/pull/3

**Comment by subdan** [comment]
@margarita-v Please try to install FigmaExport via Homebrew again.

**Comment by margarita-v** [comment]
Not it works, thank you 👍
