### ISSUE TITLE
Add support for old iOS versions

### ISSUE THREAD

**Issue by andreyoshev** [RedMadRobot/figma-export#16]
<img width="389" alt="CleanShot 2020-08-20 at 20 48 14@2x" src="https://user-images.githubusercontent.com/17673010/90794938-e0eb4980-e326-11ea-9a10-848256b8f754.png">

<img width="629" alt="CleanShot 2020-08-20 at 20 54 47@2x" src="https://user-images.githubusercontent.com/17673010/90795363-67a02680-e327-11ea-8cbd-1644b153596b.png">

Добавить #available API для поддержки цветов на старых версия системы. 

Можно вынести в yaml.

**Comment by andreyoshev** [comment]
https://github.com/RedMadRobot/figma-export/pull/17

**Comment by subdan** [comment]
Спасибо за PR. Смержил.

**Comment by andreyoshev** [comment]
Я забыл `return` :)

**Comment by subdan** [comment]
😱не работает?

**Comment by subdan** [comment]
Да, не работает.

**Comment by andreyoshev** [comment]
@subdan сейчас нормально, не заметил в строке генерации :/

**Comment by subdan** [comment]
Спасибо! Смержил и сделал релиз.
