### ISSUE TITLE
PreservesVectorData for each icon at all

### ISSUE THREAD

**Issue by Pavel-Laukhin** [RedMadRobot/figma-export#165]
Hi, fellows! 

Could you add the ability to set `preservesVectorData` for each icon in general, and not just for certain ones?

**Comment by alexey1312** [comment]
Hi! Example: we want to use one icon size in the figma library, upload to SVG and resize programmatically

**Comment by subdan** [comment]
I can add ability to use `*` symbol in the `preservesVectorRepresentation` property in the future version of FigmaExport:

Example:

`preservesVectorData` only for the tab bar icons:

```yaml
preservesVectorRepresentation:
  - "ic24TabBar*"
```

`preservesVectorData` for all the icons:
```yaml
preservesVectorRepresentation:
  - "*"
```

**Comment by subdan** [comment]
Done! Please update to the latest version (0.34.0) and try to use:
```yaml
preservesVectorRepresentation:
  - "*"
```
to set Preserves Vector Data for each icon.

**Comment by Pavel-Laukhin** [comment]
Wow! That's great! Thank you so much, Daniel!

Sorry for my long answer. I seem to be having some issues with github notifications.

Yes, you're right. This parameter is usually used to enable saving vector data for tab bar icons. But sometimes we can't be sure that the designers have made all the icons of certain sizes. Thus, there may be situations when we, the developers, will have to take care of the side ourselves. And it can be a bad situation when some images are blurred because their size is somehow changed due to rasterization. 

So now we can be sure that everything will look nice and sharp! Thank you!
