### ISSUE TITLE
figmaFrameName for colors export

### ISSUE THREAD

**Issue by ink1804** [RedMadRobot/figma-export#167]
Hello, how can I use figma-export for single frame in file? It works for icons or images, but not for colors.
`figma-export colors` exports colors from all frames i have in file.

**Comment by subdan** [comment]
Hello.

You don't need to specify a frame to export colors.

`figma-export colors` command exports colors only from Color Styles. You can see all the Color Styles of your Figma File in the right sidebar (Inspect).

<img width="247" alt="Screen Shot 2022-05-14 at 11 42 16" src="https://user-images.githubusercontent.com/410293/168418339-7ef6a0cc-37f0-4542-ae73-18fb4ec38c60.png">

To be able to export the Color Styles using FigmaExport you must publish it.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/410293/168418385-c27b2548-bd25-4cfb-9174-537962091601.png">

In the [example Figma file](https://www.figma.com/file/MRVOEjTRatddzaMN7iYlAe/FigmaExport-Example-File-%5BLight%5D?node-id=0%3A1) I added colors to a frame just for convenience, to visually show all the colors.

**Comment by ink1804** [comment]
Is it possible to export single style or several style only?
I have "Base" colors and special colors for different apps so i need to export only "Base" color and dont export "App1" and "App2" colors
It it possible?

**Comment by subdan** [comment]
There are 3 possible solutions:
1. Don‘t publish "special colors". FigmaExport exports only published Color Styles.
2. In the description field of the "special color" Color Styles type "none". FigmaExport doesn’t export Color Styles which contains a word "none" or "android".
<img width="496" alt="image" src="https://user-images.githubusercontent.com/410293/168419142-5d4fa765-d4f3-4902-95e8-af5c6b1ad5f1.png">

3. I can add an argument for `figma-export colors` command to specify a list of exported Color Styles. For example `figma-export colors -i figma-export.yaml "Base/*"` command will export only `Base` colors. This is not supported right now but I can add this in the next version of FigmaExport.

**Comment by ink1804** [comment]
Wow, third variant would be so cool! I'll waiting for it, thank you very much ^^,

**Comment by subdan** [comment]
Done! Please update to the latest version (0.34.0) and try to export colors.

**Comment by ink1804** [comment]
It works! You are the best man, thank you very much! <3
