### ISSUE TITLE
Error: valueNotFound(...stringValue..."Expected String but found null value instead"...)

### ISSUE THREAD

**Issue by Pavel-Laukhin** [RedMadRobot/figma-export#172]
Hello!

I get an error message when I try to fetch icons to XCode.
<img width="877" alt="Снимок экрана 6" src="https://user-images.githubusercontent.com/62621310/171127330-652e24c9-eedd-4f48-8022-0028f29f5033.png">

It's hard to figure out what's wrong. Could you help us with that? How can we fix that? 
Thanks in advance for your help!

**Comment by subdan** [comment]
Thanks! This issue has been fixed in 0.34.1.
