### ISSUE TITLE
illegal hardware instruction figma-export icons

### ISSUE THREAD

**Issue by Pavel-Laukhin** [RedMadRobot/figma-export#175]
Good day!

It seems that the script crashes.
![telegram-cloud-photo-size-2-5244942207528582344-y](https://user-images.githubusercontent.com/62621310/171646227-ca8535a5-b35e-4f04-b2bf-0353bbe7b1bf.jpg)

I checked the answer from api.figma.com by Proxyman, and I found that there are some empty names in components. 
<img width="1559" alt="Снимок экрана 2022-06-02 в 17 03 14" src="https://user-images.githubusercontent.com/62621310/171647289-f8b24fce-cbfa-40f7-9195-9a50dfd1b11f.png">

Could it be the reason for crashing? Is it possible to ignore those components and print their page+frame+description in a warning summary at the end of the script log?

Big thanks in advance!

**Comment by subdan** [comment]
Thanks for the issue. Fixed in [0.34.3](https://github.com/RedMadRobot/figma-export/releases/tag/0.34.3).
