### ISSUE TITLE
Error save file when download image in webp

### ISSUE THREAD

**Issue by Sx1a9z4f** [RedMadRobot/figma-export#187]
<img width="740" alt="Снимок экрана 2022-09-08 в 19 12 20" src="https://user-images.githubusercontent.com/51056548/189159788-ea978b30-419d-4458-bbc5-15c034f1485a.png">
but for png format everything is fine

**Comment by subdan** [comment]
Hi. Thanks for the issue. Could you please show me your `figma-export.yaml` file? Could you please also show me original name of the illustration (component)? Like this <img width="175" alt="image" src="https://user-images.githubusercontent.com/410293/189418676-3ca70cc6-a891-4a42-b2b6-71b71ffc9d43.png">.

**Comment by Sx1a9z4f** [comment]
<img width="567" alt="Снимок экрана 2022-09-12 в 16 27 50" src="https://user-images.githubusercontent.com/51056548/189653433-cd849157-64f5-45e4-97fb-f5f5d0df28f7.png">
<img width="188" alt="Снимок экрана 2022-09-12 в 16 28 15" src="https://user-images.githubusercontent.com/51056548/189653502-1ca74329-b8c4-4356-b885-8afecdae2cfa.png">

**Comment by subdan** [comment]
You have wrong `nameValidateRegexp`/`nameReplaceRegexp`:

When `nameReplaceRegExp` applied name becomes `illustration_card _ blocked`. Next, spaces replaced with `_`. Name becomes `illustration_card___blocked`.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/410293/189754874-007581e4-1242-459f-a528-202ac52b0232.png">

**Comment by subdan** [comment]
Hi, @Sx1a9z4f. Did you resolve the issue? Do you need additional help?

**Comment by ink1804** [comment]
I have the same issue on out gitlab ci/cd, but locally everything is fine

`Error: The file “img_132_duration_2.webp” doesn’t exist.`
regex rule not specified in figma-export.yaml file
<img width="414" alt="Снимок экрана 2023-02-28 в 12 26 18" src="https://user-images.githubusercontent.com/9392531/221796106-5982b778-180d-49f9-9ca3-bce1bf57cf2f.png">
Could you help me?

**Comment by subdan** [comment]
Do you have `cwebp` utility on your gitlab runner?

**Comment by ink1804** [comment]
That was the problem! thank you!

**Comment by pettsme** [comment]
Hey - this was an issue for me locally as well. I believe the documentation could contain some instruction on running 
`brew install webp` if the format is set to webp, especially as the error message isn't really clear that it was unable to convert the files. Maybe that can be also improved. But this thread and your answers were helpful anyway, thanks!
