### ISSUE TITLE
Provide parameter to not delete the directory when exporting

### ISSUE THREAD

**Issue by lichin-lin** [RedMadRobot/figma-export#190]
Sometime we got too many icons in one Figma Frame, so designer might split them into several Frames. That way, designer got flexibility to manage icons in different frames, developer also benefit from no need to wait too long on fetch the icons when using figma-export.

Currently, when run the export icons command, the script will clean up the whole directory first, then started to fetch icons.
Thinking if user can provide a parameter that allow `not to delete` the directory, so the behavior will be `append and replace`. 
I think here is the part where the directly got deleted (ExportIcons.swift):

```js
    if filter == nil {
        try? FileManager.default.removeItem(atPath: assetsURL.path)
    }
``` 
All the script commands should behave the same way like before, but we provide `not to clean up` logic. 
any chance we can make this behavior happen?

<img width="1459" alt="螢幕截圖 2022-09-20 上午9 57 04" src="https://user-images.githubusercontent.com/10290616/191150417-0e4939ac-8b0e-4378-b772-fd1b7d49bcb6.png">

**Comment by subdan** [comment]
Hello, @lichin-lin. To not to delete the directory just add `*` argument at the end of the command.
E.g. `figma-export icons -i ./figma-export.yaml "*" `

**Comment by subdan** [comment]
@lichin-lin did the command above work for you?

**Comment by YoungOChung** [comment]
Why is the behavior different depending on the presence or absence of a ```filter```?
Applying a ```filter``` does not add any code to the Swift file specify in ```icons.imageSwift```.

**Comment by subdan** [comment]
> Why is the behavior different depending on the presence or absence of a filter?

When you export all icons (without a filter) you want to delete icons that are no longer exist in the Figma file. To do this, **figma-export** first deletes all icons and then exports those that are in Figma file.

When you specify a filter it means that you want to export only some portion of images. So there's no need to delete anything.

> Applying a filter does not add any code to the Swift file specify in `icons.imageSwift`.

It should work. Could you give me your `figma-export.yaml` file, command you execute and screenshot of your Figma file where component names are visible?
