### ISSUE TITLE
useColorAssets false for SwiftUI colors

### ISSUE THREAD

**Issue by ichikmarev** [RedMadRobot/figma-export#192]
Is there any way, to import colors in SwiftUI project with RBG values? 
If I use `useColorAssets: false` it's only affects UIKit implementation

Color struct have this initialiser, probably it may be helpful: 
`    public init(_ colorSpace: Color.RGBColorSpace = .sRGB, red: Double, green: Double, blue: Double, opacity: Double = 1)
`

**Comment by subdan** [comment]
Hi! Unfortunately, no. But it is possible to do it. I do not have time to implement it. If you want you can create a pull request with implementation.
