### ISSUE TITLE
Unable to add some file references to Xcode project

### ISSUE THREAD

**Issue by stodevCoding** [RedMadRobot/figma-export#208]
Hi 👋

To start I want to thank you for this great solution, it's really well designed and exactly what I was looking for.

For the bug (or maybe it's normal), I have `Unable to add some file references to Xcode project` If it's useful, it's XCode 14.3, app in SwiftUI, macOS Ventura on Apple Silicon architecture.

And here is my YAML attached.
[figma-export.yaml.zip](https://github.com/RedMadRobot/figma-export/files/11299896/figma-export.yaml.zip)

Thanks again for your help

**Comment by subdan** [comment]
Is it possible to give me an access to your Figma file so I can reproduce the issue?

**Comment by subdan** [comment]
If You still have a problem please reopen the issue and I will help you.

**Comment by stodevCoding** [comment]
Sorry, I was completely swamped with work and forgot to reply. I don't remember how I managed to fix it but it's working fine. And thanks again for this wonderful tool.
