### ISSUE TITLE
Running Figma-export on Github Actions

### ISSUE THREAD

**Issue by ateek** [RedMadRobot/figma-export#219]
I did download the artifact and included it in my CI/CD setup using GitHub actions
I can see that all my icons have been downloaded correctly but the I got stuck on this step.
```
Converting SVGs to XMLs...
```
it took more than half an hour

I'm using  macos-latest github hosted runner 

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

the setup is like that
```
name: Figma Export

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      FIGMA_PERSONAL_TOKEN: ${{ secrets.FIGMA_PERSONAL_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Download Figma Export
        run: bash .github/ci/download_figma_export_artifact.sh

      - name: Run Figma Export
        run: ./Release/figma-export icons
``

**Comment by subdan** [comment]
Did you try to run figma-export locally?

**Comment by ateek** [comment]
Yeah it works perfectly fine locally.

**Comment by subdan** [comment]
Did you install vd-tool and Java Runtime on your CI?

**Comment by ateek** [comment]
Java was already installed, I added the vd-tool using this command 
```
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g vd-tool
```
https://www.npmjs.com/package/vd-tool

I still have the same problem 🤔

**Comment by subdan** [comment]
FigmaExport tries to find `vd tool` by these paths:
- `/usr/local/bin/vd-tool`
- `/opt/homebrew/bin/vd-tool`
- `./vd-tool/bin/vd-tool`

Could you please run `which vd-tool` on the CI and show me output?

**Comment by ateek** [comment]
@subdan it returns this path 
```
/Users/runner/hostedtoolcache/node/18.17.1/x64/bin/vd-tool
```

**Comment by subdan** [comment]
So FigmaExport can't find `vd-tool`. Do you have `vd-tool` near the FigmaExport?

<img width="281" alt="image" src="https://github.com/RedMadRobot/figma-export/assets/410293/5663eb30-e246-4c7c-9595-5cfdda898c65">

**Comment by ateek** [comment]
@subdan Yeah I downloaded the release from the 
https://github.com/RedMadRobot/figma-export/releases/tag/0.37.2

**Comment by ateek** [comment]
@subdan it is in the same directory as the figma-export artifact

**Comment by subdan** [comment]
> @subdan it is in the same directory as the figma-export artifact

Like this?
<img width="393" alt="image" src="https://github.com/RedMadRobot/figma-export/assets/410293/cb612a6d-01d3-4274-9931-1e7e531f467e">

**Comment by subdan** [comment]
Try to go (`cd Release`) to the `Release` directory before running FigmaExport.

**Comment by ateek** [comment]
I tried that and I'm getting this error
```
Run figma-export icons
/Users/runner/work/_temp/7fdfc922-d20d-48c4-acf8-aeff5392a255.sh: line 1: figma-export: command not found
Error: Process completed with exit code 127.
```

**Comment by subdan** [comment]
Do you have still getting the error?

**Comment by subdan** [comment]
I've tried to run FigmaExport using GitHub Actions and it works as expected:
https://github.com/RedMadRobot/figma-export/blob/temp/.github/workflows/temp.yml
https://github.com/RedMadRobot/figma-export/actions/runs/6397191232/job/17364605877

**Comment by ateek** [comment]
@subdan Thanks for your response but you are using the iOS example, not the android one, in the code you shared 
https://github.com/RedMadRobot/figma-export/blob/temp/Examples/Example/figma-export.yaml

**Comment by subdan** [comment]
Try to copy contents of `Release` directory to `/usr/local/bin` before running FigmaExport:
```
 cp -a ./figma-export-release/Release/. /usr/local/bin/
```

**Comment by ateek** [comment]
it works but couldn't find the location of the downloaded files 
```
Error: The file “ic_16_key_emergency.xml” doesn’t exist.
```

**Comment by subdan** [comment]
It seems that copying contents of `Release` directory to the `/usr/local/bin` doesn't work as expected. GitHub Actions can't find `vd-tool` command:

```
The operation couldn’t be completed. Permission denied
The file “vd-tool” doesn’t exist.
```

FigmaExport is designed to run locally, not on CI. Why do you want to run FigmaExport on CI?

**Comment by ateek** [comment]
@subdan thanks for the investigation and the insights 🙏🏽 
this is a great tool that we often use it, and it made a lot of sense to automate this

**Comment by YoungOChung** [comment]
Hello @ateek 

I'm using Github Actions similar to yours, and I have the same issue as you. How did you resolve this issue?
