### ISSUE TITLE
Tests are failing on Contents.json output

### ISSUE THREAD

**Issue by hadiidbouk** [RedMadRobot/figma-export#225]
Hey

There are two failing tests:
`testExport_preservesVectorRepresentation` & `testExport_preservesVectorRepresentation2`

It seems it's related to the generated `Contents.json` file where the properties aren't sorted correctly.

![image](https://github.com/RedMadRobot/figma-export/assets/19314956/e16eab77-72b8-4cd5-b5ef-c78ccaa42601)

**Comment by subdan** [comment]
It's weird. The tests pass without any failures [on CI](https://github.com/RedMadRobot/figma-export/actions/runs/6949385014) and my Mac.

**Comment by subdan** [comment]
Which version of Xcode you are using?

**Comment by sanghoonkim1** [comment]
I meet same problem. I am using xcode 15.0. The order of properties changes every time I export.

**Comment by subdan** [comment]
Thanks for report. The issue has been [fixed](https://github.com/RedMadRobot/figma-export/pull/230).

**Comment by mbruegmann** [comment]
Can you provide a new release including this fix?

**Comment by subdan** [comment]
@mbruegmann, done https://github.com/RedMadRobot/figma-export/releases/tag/0.37.4

**Comment by mbruegmann** [comment]
@subdan Awesome, thank you!

**Comment by mbruegmann** [comment]
@subdan Somehow the changes are not in the release. They are also not visible on the master branch:
https://github.com/RedMadRobot/figma-export/blob/master/Sources/XcodeExport/Model/XcodeExportExtensions.swift
https://github.com/RedMadRobot/figma-export/blob/master/Sources/XcodeExport/XcodeColorExporter.swift

Was it made on a fork on another repository? (see hint)
https://github.com/RedMadRobot/figma-export/blob/cea5b1f414a1b6dea76fe883aba709bcbf6d7499/Sources/XcodeExport/Model/XcodeExportExtensions.swift

Could you take a look? 🙏

**Comment by subdan** [comment]
@mbruegmann, oops, sorry. GitHub says that the branch with the fix [merged](https://github.com/RedMadRobot/figma-export/pull/230) into master but it is not. I've fixed it and make a [new release](https://github.com/RedMadRobot/figma-export/releases/tag/0.37.6). Please check.

**Comment by mbruegmann** [comment]
Works perfectly now! 🚀 Thanks @subdan !
