### ISSUE TITLE
Figma export triggers changes for SVG assets without any changes done in Figma

### ISSUE THREAD

**Issue by KulakovaE** [RedMadRobot/figma-export#237]
Hello,
We have recently noticed that figma-export is triggering changes for assets that have individual scales and PNG format on iOS. Were there some changes done recently?

<img width="795" alt="Screenshot 2024-04-04 at 15 00 24" src="https://github.com/RedMadRobot/figma-export/assets/41418577/d8653956-551a-4ad1-95ca-7c2aa1d0af8d">

**Comment by subdan** [comment]
> Were there some changes done recently?

It seems that Figma changed the way raster image are exported (like antialiasing).

**Comment by KulakovaE** [comment]
@subdan thank you for your answer.
I'm trying to understand how we can fix that 🤔
It looks like it is not one time changes, even if we merge the PR with the changes and trigger the figma export action again, we would get changes for the same files again.
