### ISSUE TITLE
Error: Figma API: Render timeout, try requesting fewer or smaller images

### ISSUE THREAD

**Issue by stodevCoding** [RedMadRobot/figma-export#240]
Hello, Three or four days ago I did an export that worked. And for the last two days, I've had a failure.

`Using FigmaExport 0.38.0 to export images to Xcode project.
2024-05-18T15:30:50+0200 info com.redmadrobot.figma-export : Fetching images info from Figma. Please wait...
2024-05-18T15:30:51+0200 info com.redmadrobot.figma-export : Fetching PNG images for scale 1.0...
2024-05-18T15:30:52+0200 info com.redmadrobot.figma-export : Fetching PNG images for scale 2.0...
2024-05-18T15:30:53+0200 info com.redmadrobot.figma-export : Fetching PNG images for scale 3.0...
Error: Figma API: Render timeout, try requesting fewer or smaller images
`
I've tried about twenty times and checked the status of the Figma APIs, and there doesn't seem to be any issues on that side.

I take this opportunity to thank you for this great solution anyway.

**Comment by subdan** [comment]
Hello. It seems that you are trying to export very large image. What is the original size of the image you are trying to export?

**Comment by stodevCoding** [comment]
Honestly since the last successful export we added a single image in 1000x1000. ^^

**Comment by subdan** [comment]
It seems that Figma API has limits when exporting raster images. Try docrease size of the image.

**Comment by stodevCoding** [comment]
Okay, I'll try it this evening and let you know. 🙏

**Comment by stodevCoding** [comment]
I put a huge timeout (500) in the yaml file and it passed. Sorry for the inconvenience. And thank you again.
