### ISSUE TITLE
Inconsistent WebP binary output when pulling assets from Figma

### ISSUE THREAD

**Issue by qonto-android-team** [RedMadRobot/figma-export#244]
Hello,

I've encountered an issue where, after pulling assets from Figma in WebP format, the generated files sometimes differ in binary format even when there are no visible changes. This inconsistency seems random, and it makes tracking changes in version control difficult. I've tried with lossy or lossless encoding but without success

**Steps to Reproduce**:
1. Pull WebP assets from Figma.
2. Observe that some assets are binary-different in consecutive pulls, even if they were not changed in Figma.

**Expected Behavior**:
WebP assets should generate consistently, resulting in the same binary file when there are no changes to the original assets in Figma.

**Actual Behavior**:
Generated WebP assets often have slight binary differences, leading to unexpected changes in version control.

**Questions**:
1. Is there a known workaround or fix to ensure consistent binary output?
2. Are there any recommended settings or configurations to stabilize the export process?

Thanks!

**Comment by subdan** [comment]
Hello. Figma API may sometimes return different binary data for the same Figma asset. It is not a FigmaExport issue. There is no workaround.
