### ISSUE TITLE
Failed when export color contain image

### ISSUE THREAD

**Issue by lichin-lin** [RedMadRobot/figma-export#26]
### issue
when exporting on [this Figma file](https://www.figma.com/file/XfqSELQ0aW3PiIg9831p7p/IOS-Design-System---experiment-for-dev?node-id=0%3A1), it failed for image color, is there any way to ignore / skip this type of color 🙂?
```
> figma-export colors
2020-09-22T10:25:52+0800 info: Using FigmaExport to export colors.
2020-09-22T10:25:52+0800 info: Fetching colors. Please wait...
Error: keyNotFound(CodingKeys(stringValue: "color", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "nodes", intValue: nil), _JSONKey(stringValue: "8:3", intValue: nil), CodingKeys(stringValue: "document", intValue: nil), CodingKeys(stringValue: "fills", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"color\", intValue: nil) (\"color\").", underlyingError: nil))
```

### version
I am using v0.13.0

**Comment by subdan** [comment]
What do you mean by image color?

I don't have permissions to view your file.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/410293/93849722-64e17a00-fcb5-11ea-9179-7d2ba1ad5da0.png">
Could you give me permission to view your file?

**Comment by subdan** [comment]
I've understood. Image color — color style created from image. To ignore this type of color style you should set description of the style to none. FigmaExport doesn‘t export a style when description = none.

<img width="231" alt="Screen Shot 2020-09-22 at 09 51 30" src="https://user-images.githubusercontent.com/410293/93851689-3f566f80-fcb9-11ea-9840-34e8d14d32b9.png"><img width="235" alt="Screen Shot 2020-09-22 at 09 51 42" src="https://user-images.githubusercontent.com/410293/93851684-3bc2e880-fcb9-11ea-952a-6ba7de1a9d35.png">

**Comment by lichin-lin** [comment]
@subdan oh, sorry I didn't aware the permission issue, I update the setting so you should see the file now 😅.
and I've try the method you provide, it works!

just a quick question, from designer's perspective, they might not going to set "none" in the description since they will need to note down important stuff in description field, would you change the rule (for example, matching a substring "none" in the whole field)?

**Comment by subdan** [comment]
Good idea. I will change the rule to match a substring.

**Comment by lichin-lin** [comment]
thanks for the update! really like this repo!
