### ISSUE TITLE
FigmaExport doesn't delete old resources (Android)

### ISSUE THREAD

**Issue by subdan** [RedMadRobot/figma-export#28]
There is a Figma file with 50 icons.
Export the icons to an Android project.
Remove 10 icons from Figma.
Export the icons to the Android project again.
**Deleted icons are not deleted from the Android project.**

There was an idea to make nested folders inside drawable, for example `drawable/icons`, but it is prohibited.

**Comment by osipxd** [comment]
It is possible to create a nested folder in `res` dir for figma-export purposes. It will contain own `drawable` and `values` directories.
But this approach requires additional configuration line in a build script:
```groovy
android {
  sourceSets {
    res.srcDirs += "src/main/res/{needed_directory_name}"
  }
}
```

**Comment by subdan** [comment]
Cool! I will try to use your solution.

**Comment by osipxd** [comment]
I missed `main` in the snippet. Fixed now

**Comment by osipxd** [comment]
I missed main in the snippet. Fixed now
