### ISSUE TITLE
Add the ability to pass `personalAccessToken` via environment variable

### ISSUE THREAD

**Issue by modestman** [RedMadRobot/figma-export#3]
Storing the `figma.personalAccessToken` in configuration file in repository is insecure. Please add the ability to pass `personalAccessToken` via environment variable. If property defined in both file and env variable then use environment variable value.

**Comment by subdan** [comment]
How a user will set a personalAccessToken?

**Comment by modestman** [comment]
in terminal or `.bash_profile`:
```shell
export FIGMA_ACCESS_TOKEN=value
```

in CI server, environment variables passed through secrets in repository

**Comment by subdan** [comment]
Cool. A user who uses Fastlane could add `FIGMA_ACCESS_TOKEN` in the `.env` file.
