### ISSUE TITLE
Unable to execute commands in powershell

### ISSUE THREAD

**Issue by andres-j** [RedMadRobot/figma-export#33]
Trying to give the tool a whirl but having issues running the application in the terminal. 

1. I downloaded the latest release today and unzipped the contents to C:\Program Files\FigmaExporter\ 
2. Set personal figma token as an env variable
3. Open powershell in the directory containing figma-export binary and the vd-tools directory
4. Enter "figma-export init --platform android" to create config
5. Instead of the config file being created in the directory, the system attempts to 'open' the figma-export binary. No file is created / the binary does not run

Gotta be missing something - any help would be appreciated. thank you!

**Comment by subdan** [comment]
Hello, @andres-j. FigmaExport works only on macOS.

**Comment by andres-j** [comment]
ha! that would explain that. Thanks!
