### ISSUE TITLE
Use wildcard on export

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/figma-export#34]
It would be great to be able to export icons or illustrations matching wildcard:
```shell
figma-export images "200x200/*" # Export all illustrations 200x200
figma-export icons "32/navigation/*" # Export all navigation icons
```

**Comment by subdan** [comment]
FigmaExport already support it.
https://github.com/RedMadRobot/figma-export#arguments
Did you check it?

**Comment by osipxd** [comment]
Hm, I'll check it again, thanks

**Comment by osipxd** [comment]
Fine, it works!
