### ISSUE TITLE
Add support for iPad idiom when exporting images / icons

### ISSUE THREAD

**Issue by lichin-lin** [RedMadRobot/figma-export#36]
### 🚀  Feature request
Sometime, Designer might want to have a different kind of image show up for iPad platform compare to iPhone platform
for example: different size / different color or shape...etc

will it be possible to support this feature for iOS, so the developer can see something like this (idiom shows either `iphone` or `ipad` instead of `universal`):

<img width="1435" alt="截圖 2020-10-20 上午11 05 04" src="https://user-images.githubusercontent.com/10290616/96536424-a1a98c80-12c6-11eb-937a-514067573ad4.png">

### 💡 Possible solution
To achieve the feature, we can use some kind of naming convention, I suggest that we can make designer control the idioms by using the `~` tilde symbol:

<img width="1101" alt="截圖 2020-10-20 上午11 08 36" src="https://user-images.githubusercontent.com/10290616/96536928-afabdd00-12c7-11eb-9f02-b9eb5b5a6ac7.png">

as the image shows, we can combine them into same imageset when parsing, and note different idiom in `content.json`.

with this tilde naming convention, I think there will be more flexibility for image / icons to show up for different platform.

**Comment by lichin-lin** [comment]
Hi @subdan, would like to know if there will be any update relative to this feature request, or is there anything I can help with 🙂

**Comment by subdan** [comment]
Hi. I’m busy right now. I plan to make this feature in November.
Do you know Swift?

**Comment by lichin-lin** [comment]
we've look into how the process worked in (`AssetsProcessor.swift`), it is quite hard to add grouping feature (img/some-img, img/some-img~ipad,...) in with current architecture, we might need to modify the struct in `Image.swift`, (for example, add **basename** and **idiom** Property) which seems will make too much changes 😓
