### ISSUE TITLE
Fonts figma export for android studio

### ISSUE THREAD

**Issue by ArshaWIN** [RedMadRobot/figma-export#42]
Icons must be exported to font directory (the same root level as drawable directory) as ttf files. Names must have snake case style. One font ttf file for each font style. Example in the image below.
<img width="312" alt="Screenshot 2020-11-24 at 12 01 36" src="https://user-images.githubusercontent.com/12299870/100072252-0d928e00-2e4d-11eb-8307-58a8cf574b70.png">

**Comment by subdan** [comment]
It is a user responsibility to download and move fonts to Android Studio project.
Figma API doesn't provide ability to get ttf file.

**Comment by subdan** [comment]
I’am closing the issue. If you have any questions feel free to reopen the issue.
