### ISSUE TITLE
Add On-Demand Resource Tags support

### ISSUE THREAD

**Issue by NoFearJoe** [RedMadRobot/figma-export#47]
Do you plan to add on-demand resource tags support in the nearest future?

**Comment by subdan** [comment]
I don‘t plan to add this feature because almost all iOS apps store resources locally.

**Comment by NoFearJoe** [comment]
What if I'll make a pull request with this feature? Or it's better to ask you to implement this?

**Comment by subdan** [comment]
It'll be cool. I will be glad to accept your PR. I don‘t plan to implement it myself.

I want to ask you some questions before you start.

1. How will the designer specify the tags for a group of resources in Figma file?

2. Which project files do you want to edit/add? E.g. edit `*.pbxproj` and `*.imagset/Contents.json`.

3. How a programmer can get access to the on-demand resources? Do you plan to generate code to obtain these resources?

4. Does Android have a similar feature? Do you plan to implement only iOS part?

**Comment by NoFearJoe** [comment]
1. I haven't thought about it yet. Maybe it will be implemented with a separated frame with a special prefix (`on-demand`, for example). But first I have to dive into your code to better understand how to implement this.
2. I guess I will only add tags to `*.imagset/Contents.json`.
3. Are you asking about obtaining the resources in runtime?
4. No, I don't, because I haven't heard about this feature on Android.

**Comment by subdan** [comment]
1. I think we should add tags to the description field of a component.
2. When you add tag to a resource in an Assets.xcassets file, pbxproj file is also modified.
3. Yep.
5. Do you want to use [Prefetching Tags](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/Tagging.html)?

**Comment by subdan** [comment]
Hi, @NoFearJoe. Do you still want to implement this feature?

**Comment by NoFearJoe** [comment]
We've stopped implementing this feature in our project. So I am not going to implement On-Demand resources in near future.
