### ISSUE TITLE
Failed when export anything

### ISSUE THREAD

**Issue by fvonk** [RedMadRobot/figma-export#56]
When I export I get this error. What I can do?

Using FigmaExport to export colors.

> Error: keyNotFound(CodingKeys(stringValue: "fontExtensionDirectory", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "ios", intValue: nil), CodingKeys(stringValue: "typography", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"fontExtensionDirectory\", intValue: nil) (\"fontExtensionDirectory\").", underlyingError: nil))

It is in your Example iOS Demo Project.

**Comment by subdan** [comment]
Which version of FigmaExport do you use?
`figma-export --version`

**Comment by subdan** [comment]
I've removed `fontExtensionDirectory` property in 0.12.0 version. Please update FigmaExport to the latest version.

**Comment by fvonk** [comment]
Thanks, I've updated figma-export to 0.18.5 and now have slightly another error:

> Error: keyNotFound(CodingKeys(stringValue: "xcodeprojPath", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "ios", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"xcodeprojPath\", intValue: nil) (\"xcodeprojPath\").", underlyingError: nil))

appreciate for any help.

**Comment by subdan** [comment]
I added `xcodeprojPath` parameter to FigmaExport since 0.13.0. Read [documentation](https://github.com/RedMadRobot/figma-export/blob/master/CONFIG.md) for actual config.

**Comment by fvonk** [comment]
Okay) thanks

Now: 

2020-12-18T21:13:26+0300 info com.redmadrobot.figma-export : Using FigmaExport to export colors.
2020-12-18T21:13:26+0300 info com.redmadrobot.figma-export : Fetching colors. Please wait...

> Error: keyNotFound(CodingKeys(stringValue: "color", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "nodes", intValue: nil), _JSONKey(stringValue: "739:0", intValue: nil), CodingKeys(stringValue: "document", intValue: nil), CodingKeys(stringValue: "fills", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"color\", intValue: nil) (\"color\").", underlyingError: nil))

Where I can find documentation about this part ?

**Comment by subdan** [comment]
The error says that you have incorrect Figma's Color Style. Read [Design requirements](https://github.com/RedMadRobot/figma-export#design-requirements).

Did you publish color styles to the team library?
<img width="447" alt="image" src="https://user-images.githubusercontent.com/410293/102648169-14749e00-4178-11eb-9037-ce3604d128c7.png">

All the Color Styles in your FIgma file should consist of only solid colors. There shouldn't be gradients or bitmap fills.

Could you please give me an access to your Figma file so I can check it?

**Comment by fvonk** [comment]
Thanks, I'm ready to close the issue. But we cannot export images:

> 2020-12-21T15:00:17+0300 info com.redmadrobot.figma-export : Using FigmaExport to export images to Xcode project.
> 2020-12-21T15:00:17+0300 info com.redmadrobot.figma-export : Fetching images info from Figma. Please wait...
> Error: Components not found in the Figma file. Have you published Components to the Library?

In Figma we have Images in separate Page. Could this be the reason. ?

**Comment by subdan** [comment]
What is your Figma [plan](https://www.figma.com/pricing/)? Free, Professional or Organization?
FigmaExport uses Shareable team libraries which available only for Professional and Organization plan.

**Comment by fvonk** [comment]
It's Professional.

**Comment by subdan** [comment]
Ensure that you have published all the images to your team library.

Open Team Library:
<img width="271" alt="Screen Shot 2020-12-21 at 15 12 04" src="https://user-images.githubusercontent.com/410293/102775937-e9b85e80-439e-11eb-8254-faa60257915d.png">

Choose your Library:
<img width="483" alt="Screen Shot 2020-12-21 at 15 12 27" src="https://user-images.githubusercontent.com/410293/102775971-fc329800-439e-11eb-9892-2f514932a671.png">

Ensure that the Library contains all the images:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/410293/102775991-048ad300-439f-11eb-9b01-0c63c013c38a.png">

**Comment by fvonk** [comment]
Ok, Thank you. We will try to move images to the same page as icons.
