### ISSUE TITLE
How do you build figma-export from source?

### ISSUE THREAD

**Issue by NoahHines** [RedMadRobot/figma-export#63]
Hello, I have some feature ideas I'd like to play with. I've forked and cloned the repo, but I can't figure out what commands to run to build a local binary.

What is the workflow to make changes and test? Thanks!

**Comment by subdan** [comment]
Hello.
1. Double click on `Package.swift` file to open the project in Xcode.
2. Wait until SPM completes installing dependencies.
3. Edit Scheme `figma-export`
<img width="309" alt="image" src="https://user-images.githubusercontent.com/410293/106238659-4dda0800-6212-11eb-962f-2127a6a95bbc.png">
4. Choose Run and select Arguments. Add arguments and environment variables:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/410293/106238717-69dda980-6212-11eb-9130-83aad5423915.png">
Environment variables:

- FIGMA_PERSONAL_TOKEN — Generate a personal Access Token through your user profile page or on Figma API [documentation website](https://www.figma.com/developers/api#access-tokens). 

Arguments:

- Read [README.md](https://github.com/RedMadRobot/figma-export#arguments) for more info. On the screenshot above I add three arguments to export icons for example project located in `./Examples/Example` directory.
5. Choose **Options** next to the **Arguments**.
<img width="959" alt="Screen Shot 2021-01-29 at 09 19 13" src="https://user-images.githubusercontent.com/410293/106239096-17e95380-6213-11eb-8c81-7c5b870d8acf.png">

Enable **Working Directory** option and specify a path to example project. Example `/Users/subdan/Documents/RMR/projects/figma-export/Examples/Example`

6. Press CMD+R to compile and run `figma-export` for specified example project.

7. See logs.
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/410293/106239617-fc327d00-6213-11eb-9cb7-326435379c12.png">

**Comment by NoahHines** [comment]
Thanks Daniil! That worked perfectly.
