### ISSUE TITLE
[Question] Support multiple pages

### ISSUE THREAD

**Issue by SergeyKovalenko** [RedMadRobot/figma-export#70]
Thank you for such a great tool? It saves a ton of time.

I have a couple of questions:
- Is it possible to import assets from different pages?  Is there any way to specify a page for import in the config file?

![image](https://user-images.githubusercontent.com/872805/107756552-0af95380-6d2d-11eb-89b0-de650ed8d241.png)

- Do you have any requirements on how the Figma frame should be named?  For example, "Body status emoji", is it a valid name?
I don't know why but currently, I'm able to import only from the frames on the "Components" page.

**Comment by subdan** [comment]
Hi. Thanks. 

> Is it possible to import assets from different pages? Is there any way to specify a page for import in the config file?

No. You can specify only `common.icons.figmaFrameName` and `common.images.figmaFrameName` options. All the icons/images must be placed in a single frame on a single page.

> Do you have any requirements on how the Figma frame should be named? For example, "Body status emoji", is it a valid name?

If you export icons (`figma-export icons`) and do not specify custom frame name, frame must be named `"Icons"`.
If you export images (`figma-export images`) and do not specify custom frame name, frame must be named `"Illustrations"`.
See example in the Figma example file [here](https://www.figma.com/file/BEjfU0kCVnPqXdRLfoLvkf/FigmaExport-Example-File-Light).
You can set custom frame name in the [config file](https://github.com/RedMadRobot/figma-export/blob/master/CONFIG.md). See `common.icons.figmaFrameName` and `common.images.figmaFrameName`.

**Comment by SergeyKovalenko** [comment]
We have two frames with icons "Icon" and "Body status" on the different pages.  
When I specify custom `figmaFrameName Icon` everything works like a charm. 
But when I change it to `figmaFrameName Body status` i see `Components not found in the Figma file. Have you published Components to the Library?` 
That's why am I wondering maybe it depends on the page name,  since  `Icon` frame, and `Body status` added to different pages.

**Comment by subdan** [comment]
> But when I change it to figmaFrameName Body status i see Components not found in the Figma file. Have you published Components to the Library?

It must works. I've checked it.

```
common:
  icons:
    figmaFrameName: Body status
```

<img width="346" alt="Screen Shot 2021-02-12 at 14 12 57" src="https://user-images.githubusercontent.com/410293/107761435-6aab2b00-6d3c-11eb-9963-d64140fdd841.png">

> That's why am I wondering maybe it depends on the page name, since Icon frame, and Body status added to different pages.

No. I've checked. I moved "Body status" frame to "Page 2" and it still works.

> Is it possible to specify custom frame name with whitespaces (e.g. "My Icons")?

Yes.

**Comment by SergeyKovalenko** [comment]
Got it.  Thank you!

**Comment by subdan** [comment]
Cool! If you will have any questions feel free to contact me.
