### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by mikhaylenko-nikita-sergeevich** [RedMadRobot/figma-export#72]
Я правильно понимаю, что это приложение только под MacOS? Есть ли планы по поддержке windows версии?

**Comment by subdan** [comment]
Да, поддерживается только macOS. Планов по поддержке Windows версии нет.

FigmaExport написана c помощью Swift и SPM. Как только Apple портирует SPM под Windows я попробую добавить поддержку Windows.

https://swift.org/blog/swift-on-windows/
https://swift.org/package-manager/
