### ISSUE TITLE
How to debug Illegal hardware instruction

### ISSUE THREAD

**Issue by si-hartmann** [RedMadRobot/figma-export#83]
We discover an illegal hardware instruction error. Is there any way to debug this efficiently? Are you planing on implementing a verbose mode?

**Comment by subdan** [comment]
Hello. This error says that FigmaExport crashed. To fix this issue could you please show me your config file and if possible link to the Figma file.

**Comment by si-hartmann** [comment]
I got the error by running the project from Xcode. It was an Umlaut ("Ü") in one of the asset names. This could be caught and handled in XcodeExportExtensions:makeFileURL. 

Thanks for this project! 👍
